version: "3"
services:

  web:
    image: flask-webapp:latest
    build: .
    container_name: gunicorn
    ports:
      - "8080:8080"
    environment:
      - LETSENCRYPT_EMAIL=chr.unterrainer@gmail.com
      - LETSENCRYPT_HOST=christianunterrainer.com
      - VIRTUAL_HOST=christianunterrainer.com
      - VIRTUAL_PORT=8080
      - NGINX_WEB=nginx-web
      - DOCKER_GEN=nginx-gen
      - LETS_ENCRYPT=nginx-letsencrypt

  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./webapp:/webapp
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/vhost.d:/etc/nginx/vhost.d
      - ./etc/html:/usr/share/nginx/html
      - ./etc/nginx/certs:/etc/nginx/certs:ro
      - ./etc/nginx/htpasswd:/etc/nginx/htpasswd:ro
    depends_on:
      - web
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/certs:/etc/nginx/certs:ro
      - ./etc/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - ./etc/vhost.d:/etc/nginx/vhost.d
      - ./etc/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  nginx-letsencrypt:
    depends_on:
      - nginx-gen
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ./etc/conf.d:/etc/nginx/conf.d
      - ./etc/nginx/certs:/etc/nginx/certs:rw
      - ./etc/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/vhost.d:/etc/nginx/vhost.d
      - ./etc/html:/usr/share/nginx/html
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-web
    logging:
      driver: json-file
      options:
        max-size: "4m"
        max-file: "10"

networks:
  default:
    external:
      name: webproxy
